### ISSUE TITLE
No solution for steel ingot found, what am I doing wrong?

### ISSUE THREAD

**Issue by ZeeOcho** [rockfactory/satisfactory-logistics#21]
I have a basic setup for Alternate: Solid Steel Ingot (2 Coal + 2 Iron Ingot => 3 Steel Ingot).

The way I set in up in Satisfactory Logistics is:

Coal "Factory": In 900 World-Coal, out 900 Coal
Iron Ingot Factory: In 1920 World Iron Ore, out 1920 Iron Ingots

Steel Ingot Factory: in 900 Coal-Factory-Coal, 1920 Iron-Ingot-Factory-Ingots, out: 300 Steel Ingots. I made sure I have selected the Alternate: Solid Steel Ingot (I also delesected all converting recipes). But the calculator does not find any result. Where am I fucking up?

![image](https://github.com/user-attachments/assets/74e47c8a-01a7-4eec-8a2f-70e7cd21967a)

**Comment by rockfactory** [comment]
Could you try enabling all recipes (except for steel ingot alts, keep only Solid Steel Ingot) and all world resources in the Limitations tab?

![image](https://github.com/user-attachments/assets/1ea1ba8c-7a90-4747-93d2-a0dd4b417a65)
![image](https://github.com/user-attachments/assets/7b67c4b5-dc44-4d9d-8f42-cc04974e40d2)

**Comment by ZeeOcho** [comment]
Sure thing!

That works and gives the result I was looking for. It also correctly uses the outputs from the Iron/Coal Factories. As soon as I disable Coal (and Oil) as a world resource, So this was I was doing wrong, apparently. I expected that the coal output from that input factory would still be available.

Thank you for your help :)!

**Comment by rockfactory** [comment]
> Sure thing!
> 
> That works and gives the result I was looking for. It also correctly uses the outputs from the Iron/Coal Factories. As soon as I disable Coal (and Oil) as a world resource, So this was I was doing wrong, apparently. I expected that the coal output from that input factory would still be available.
> 
> Thank you for your help :)!

I understand that inputs VS world resources is a bit misleading; right now there is, for example, no way to limit world resources amount, the calculator would always try to use the world resources if allowed (even in inputs are insufficient).

I'm working on this together with input maximization, hope it will make it easier, I'll share progress on the Discord if you'd like to give us some feedback https://discord.gg/Crd8r87dwY

**Comment by rockfactory** [comment]
Hi! Just wanted to let you know that in upcoming release (v0.8.0), your setup will be working fine (Limited Input + Disabled World Resource)
