### ISSUE TITLE
[Feature proposal] Maximize Output(s)

### ISSUE THREAD

**Issue by ZeeOcho** [rockfactory/satisfactory-logistics#22]
When opening a calculator for a factory, you can use "Auto-set from Plan" to automatically adjust inputs for the given outputs (basically minimizing inputs).

A function might be helpful that does the other way round for inputs: "Auto-set from inputs", which would the give you the maximum amount for each output that can be achieved with the given inputs.

**Comment by rockfactory** [comment]
Hi, thanks for the suggestions, maximization is already in progress luckily! See #20 and https://satisfactorylogistics.featurebase.app/it/p/maximize-output-based-on-input

**Comment by ZeeOcho** [comment]
Awesome!

And I didn't realize you have a different place for feedback. My own programmers' brain just saw "git" and went there :).

**Comment by rockfactory** [comment]
Released!
