### ISSUE TITLE
Button background missing

### ISSUE THREAD

**Issue by elonmir** [rockfactory/satisfactory-logistics#3]
### Description
The summary button in the calculator view is missing a background color.

### Expected Outcome
Button should have a backfill.

### Additional Context
![image](https://github.com/user-attachments/assets/d04daeb2-0bb8-487d-9b58-e17fb2c94300)

**Comment by rockfactory** [comment]
You are right; I'm working on changing the buttons UI (they are too many right now and a bit sparse) in the Solver

**Comment by elonmir** [comment]
Yeah just though to document stuff as I come across it. Hope that's ok

**Comment by leonardfactory** [comment]
For sure, I just wanted to provide some context about this one; any contribution is highly appreciated!

**Comment by rockfactory** [comment]
Resolved in v0.7.0
